<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container73Uy8QF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container73Uy8QF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container73Uy8QF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container73Uy8QF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container73Uy8QF\App_KernelDevDebugContainer([
    'container.build_hash' => '73Uy8QF',
    'container.build_id' => '1cb3513f',
    'container.build_time' => 1614516005,
], __DIR__.\DIRECTORY_SEPARATOR.'Container73Uy8QF');
