<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHHfE0ck\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHHfE0ck/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHHfE0ck.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHHfE0ck\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHHfE0ck\App_KernelDevDebugContainer([
    'container.build_hash' => 'HHfE0ck',
    'container.build_id' => '1ba69a56',
    'container.build_time' => 1614310000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHHfE0ck');
