<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQf9mpCY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQf9mpCY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQf9mpCY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQf9mpCY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQf9mpCY\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qf9mpCY',
    'container.build_id' => 'f318181c',
    'container.build_time' => 1614215203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQf9mpCY');
